name: Build and Publish Container Images

on:
  push:
    branches: [master, ci]
    paths-ignore:
      - '**.rst'
      - '.gitignore'
      - 'LICENCE'
      - 'licence_*'

jobs:
  build_images:
    name: Build Container Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [oldlibs]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build -t "${{ matrix.image }}" .

      - name: Login to Registry
        if: >
          github.event_name == 'push'
          && github.ref == 'refs/heads/master'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Upload Image
        if: >
          github.event_name == 'push'
          && github.ref == 'refs/heads/master'
        run: |
          registry="$(echo "ghcr.io/${{ github.repository }}/" | tr '[:upper:]' '[:lower:]')"
          remote_image="${registry}${{ matrix.image }}"
          docker tag "${{ matrix.image }}":latest "${remote_image}":latest
          docker image push "${remote_image}":latest
